<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>WyyPlayer.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="WyyPlayer.Core.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.2.1" />
    <PackageReference Include="NLayer" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WyyPlayer.Api\WyyPlayer.Api.csproj" />
  </ItemGroup>
</Project>